### ISSUE TITLE
Ball Shooter Mechanism - Uses two motors

### ISSUE THREAD

**Issue by Cyco12** [ResetRobotics/2017-robot-code#1]
We need to setup a basic framework for the Ball Shooter Mechanism. It uses two motors; one to move wheel that shoots ball and one to rotate the end of the ramp.

**Comment by leejasper851** [comment]
We need to decide what our feeder mechanism will be - motor or piston.

**Comment by leejasper851** [comment]
How will the second motor fit? The one that controls the adjustments. Also, we need to do the calculations from the vision tracking to decide from what angle we need to shoot. And we need to decide how to turn an angle number to a motor position.

**Comment by leejasper851** [comment]
Steps for coding the ball shooter mechanism. First, we need to decide when to start it up, and then start up the shooting wheel. We calculate the time until it reaches our wanted speed and wait that time. Then, we need to take in measurements from vision tracking and make calculations to find the angle and the position of our robot (moving or turning). We'll do more calculations to find which motor position (adjustment motor) matches the angle. Then, we activate the feeder, either a wheel or piston. We're going to have a way to completely stop shooting. In that case, we'll  unactivate the feeder, and then the shooting wheel. I'll add this to the description once we find our feeder method. We will have a button that drivers press to start up the mechanism and to stop it.

**Comment by leejasper851** [comment]
We need to get the shooter code that Cole wrote to work. It's unfinished.
