### ISSUE TITLE
Climbing Mechanism - Uses one motor

### ISSUE THREAD

**Issue by Cyco12** [ResetRobotics/2017-robot-code#2]
The Climbing Mechanism uses one motor. This mechanism should use our climbing design and allow for motor control to climb the rope

**Comment by leejasper851** [comment]
We need to be able to start the motor (moving forwards) and stop it. It should be able to turn backwards just in case we'll need it. We will need 3 buttons. One will make the motor turn forward and another vice versa. One will make the motor stop.
