### ISSUE TITLE
Gear Mechanism - Uses one piston

### ISSUE THREAD

**Issue by Cyco12** [ResetRobotics/2017-robot-code#3]
The Gear Mechanism uses one piston to open and close the flap that grabs the gear.

**Comment by leejasper851** [comment]
The drivers will see if the vision tracking tape for the peg can be easily seen by the robot and press a button. Then, the robot will do an automated process. It will have to line itself up with the tape, move forward, open the contraption by stretching the piston, move sideways, back up, and close the contraption by squeezing the piston in. We will have another button to open and close the contraption just in case the automated process messes up. We'll then be able to do it manually, with the drivers implementing all the steps.
