### ISSUE TITLE
Mecanum Wheels 

### ISSUE THREAD

**Issue by Cyco12** [ResetRobotics/2017-robot-code#4]
Use wpilib's basic mecanum function that is built in and replace later

**Comment by leejasper851** [comment]
We need to decide how we'll flip the robot over.

**Comment by leejasper851** [comment]
The mechanum drive will be controlled with a 2D joystick. Whatever direction it tilts will be the direction the robot moves. We will have to be able to calculate the joystick angle and control the 4 motors accordingly. Additionally, the mechanum wheels will have to be able to take instruction from the other contraptions. Gear: It will have to follow the instructions of the automated process described in the gear description. Ball: It will have to follow specific instructions to align itself with the boiler. Climbing: It will have to be able to turn over, precisely, perfect every time. It will also have to be able to align itself with the rope, but this will be done manually by the drivers.

**Comment by valence55** [comment]
done
